runtime: nodejs18
instance_class: F1

handlers:
- url: /
  static_files: client/dist/index.html
  upload: client/dist/index.html

- url: /(.*)
  static_files: client/dist/\1
  upload: client/dist/(.*)

- url: /.*
  script: server/app.js
