runtime: nodejs18
env: standard

# Serve static files from the 'dist' directory.
handlers:
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html

- url: /(.*\.(css|js|png|jpg|gif))$
  static_files: dist/\1
  upload: dist/(.*)
